order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
product_attribute:
    resource: "@ProductAttributeBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
api_login_check:
    path: /api/login_check
