# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    ProductAttributeBundle\DataFixtures\ORM\:
        resource: '../../src/ProductAttributeBundle/DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']
    ProductBundle\DataFixtures\ORM\:
        resource: '../../src/ProductBundle/DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']